### PR TITLE
feat: implement storing images in firebase

### PR DESCRIPTION
**Pull request by Ismaillat**
Image viewModel and repository

### CODE REVIEW

**Review by othbcq — CHANGES_REQUESTED** [review]
### PR Review

Great work on implementing the `FirebaseImageRepository`, `ImageRepository`, and `ImageViewModel`! The structure is well-organized. I’ve reviewed the code and identified a few areas where some small improvements could be made.

#### Suggested Changes

---

#### 1. Add Null Check for `imageFile` in `uploadImage` in `ImageViewModel`

   - **Issue**: The `uploadImage` method in `ImageViewModel` accepts a nullable `imageFile`, but it doesn’t check for null before accessing it. This could lead to a `NullPointerException` if `uploadImage` is called with a null file, potentially crashing the app.
   - **Suggested Change**: Add a null check for `imageFile` at the beginning of `uploadImage`. If the file is null, update the status to indicate an error and return immediately. This ensures that the method handles null cases gracefully.

   ```kotlin
   fun uploadImage(imageFile: File?) {
       if (imageFile == null) {
           _uploadStatus.value = UploadStatus(isLoading = false, errorMessage = "Image file is null")
           return
       }
       _uploadStatus.value = UploadStatus(isLoading = true)
       viewModelScope.launch {
           val result = repository.uploadImage(imageFile)
           _uploadStatus.value = if (result.isSuccess) {
               UploadStatus(isLoading = false, downloadUrl = result.getOrNull())
           } else {
               UploadStatus(isLoading = false, errorMessage = result.exceptionOrNull()?.message ?: "Unknown error")
           }
       }
   }
```
---

#### 2. Improve Error Handling in FirebaseImageRepository

  - **Issue**: Currently, if an error occurs during image upload in FirebaseImageRepository, the exception message returned is generic. Adding more context to error messages will make it easier for users to understand what went wrong, and for developers to debug if necessary.
- **Suggested Change**: 
Add detailed error messages and log exceptions for better troubleshooting. This change will also make it easier to debug issues related to file upload failures.

```kotlin
override suspend fun uploadImage(imageFile: File): Result<String> {
    if (user == null) {
        return Result.failure(Exception("Failed to upload image: User not signed in."))
    }
    return try {
        val bytes = imageFile.readBytes()
        val fileRef = storageRef.child("/images/$userMail/${imageFile.name}")
        fileRef.putBytes(bytes).await()
        val downloadUrl = fileRef.downloadUrl.await()
        Result.success(downloadUrl.toString())
    } catch (e: Exception) {
        Log.e("FirebaseImageRepository", "Image upload failed", e)
        Result.failure(Exception("Failed to upload image: ${e.localizedMessage}"))
    }
}
```

--- 
#### 3. Convert userMail to Lowercase

- **Issue**: Since Firebase Storage paths are case-sensitive, using mixed-case email addresses in paths could lead to unintended duplicate folders or access issues. Converting userMail to lowercase would help avoid such issues by ensuring consistent folder naming.
- **Suggested Change**: 
Convert userMail to lowercase when assigning it in FirebaseImageRepository.

```kotlin
private val userMail = user?.email?.lowercase() ?: "unknown"

```
---

#### 4. Add Documentation as per Milestone 1 Feedback

- **Issue**: It would be beneficial to add documentation for the ImageRepository interface and its methods, as requested in the Milestone 1 feedback.

**Review by mehdi-hamirifou — CHANGES_REQUESTED** [review]
Great work on implementing the image upload functionality with Firebase integration. I agree with Othmane's review and would like to suggest a few additional improvements to enhance code readability and ensure correctness:

- In ImageReviewScreen.kt: Currently, imageUri is named as though it’s of type Uri, but it’s actually a File?. Consider renaming it to imageFile or something similarly descriptive to avoid confusion.

- In FirebaseImageRepositoryTest: Add tests that simulate both success and failure scenarios for the repository’s uploadImage function. This will help ensure the function behaves as expected and can handle different cases robustly.

**Review by mehdi-hamirifou — APPROVED** [review]
Everything looks good to me now, well done ! Approved for merge.

**Review by othbcq — APPROVED** [review]
Excellent job with the adjustments! The code looks solid and well-documented now. Ready to merge. Well done!

**Pull request merged**
