### PR TITLE
Implement posts viewmodel and repository

### LINKED ISSUE #102: Implement Posts View Model and Repository
As a user, I want to view, add, and interact with posts in the feed so that I can stay updated with the latest content and share my own.

**Acceptance Criteria:**
- Posts: The feed dynamically shows posts fetched from the repository with correct data (username, URI, likes).
- Add Post: Users can add posts, which are saved to Firestore via the repository.
- Select Post: Selecting a post updates the ViewModel’s selected state.
- Error Handling: Display error messages if fetching or adding posts fails.
- Unique IDs: A new unique ID is generated for each post.
- Tests: Unit tests verify that the ViewModel correctly interacts with the repository for fetching, adding, and selecting posts.

### PR DESCRIPTION
**Pull request by rihabbelmekki**
This pull request implements the `FeedViewModel` and `FeedRepository`, which are responsible for managing and interacting with the feed data in the application. The `FeedViewModel` handles the logic for the UI, while the `FeedRepository` manages data fetching and updates from the data source.

**Changes:**
- Added `FeedViewModel` with methods to fetch and add posts.
- Created `FeedRepository` to interact with the Firestore database and manage feed-related operations.
- Implemented unit tests for both `FeedViewModel` and `FeedRepository`.
  - Tests include verifying repository interactions and ensuring proper state updates in the `FeedViewModel`.

**Testing:**
All unit tests are passing, including tests for repository methods and view model interactions. The tests use mocking and coroutines for proper async handling.

**Related issues:**
Closes #102

### CODE REVIEW

**Review by raniabbrk — APPROVED** [review]
Great code! The FeedViewModel and FeedRepositoryFirestore classes are well-integrated, with clear methods for managing posts and handling user authentication status.
This PR is approved for merging. Next week, as discussed, we plan to implement location-based functionality for the feed. Here are some ideas for the next phase:
-  Adding a location property to the Post data class, possibly containing latitude and longitude, will enable us to implement a location-based feed in the future.
- Distance Calculation Method: We may want to add a method in FeedRepository to calculate the distance between the user and each post, allowing us to filter or sort the feed by proximity.
Overall, this PR is very solid for the current requirements and provides a good foundation for further enhancement.

**Review by raniabbrk — CHANGES_REQUESTED** [review]
Great code! You did a really good job at implementing the view model's and repository's functions and making them very straightforward. Also props to you for thinking about implementing a generateNewuid function and making the Uid an attribute of a post. This makes your code clear and will be very useful for the next steps. However, I noticed just a few small things that you should fix before merging:
- The title of your classes and directories are slightly misleading as these concern posts of the app in general, and not necessarily just the feed. You should  change the "feed" directory to "post" and for each file, instead of having "Feed", replace it by "Posts" ( FeedRepository.kt should be renamed to PostsRepository.kt for example).
-  Add a location property to the Post data class, possibly containing latitude and longitude, which will enable us to implement a location-based feed in the future.

Overall, this PR is very solid. Good job!

**Review by raniabbrk — APPROVED** [review]
You did a good job at fixing the issues, and updating the test names for consistency was a good initiative. Approved for merge.

**Comment by rihabbelmekki** [comment]
I am merging this PR despite it not fully meeting the required coverage. The changes are essential to move forward with our work, and I'll prioritize adding the necessary tests in a follow-up PR to bring coverage up to standard.

**Pull request merged**
