### PR TITLE
 Implement Dynamic Labels with Billboard Effect for OpenGL Renderables

### PR DESCRIPTION
**Pull request by AdrienBousquieEPFL**
## Description
This PR introduces a feature to dynamically render labels (e.g., star or planet names) on objects in the OpenGL screen. The labels automatically adjust their orientation and size based on the camera's view, ensuring they remain readable regardless of zoom level.

### Key Features
- **Dynamic Label Rendering**: Labels adapt to the camera's position and orientation using a billboard effect.
- **Adjustable Scaling**: Added size parameter to `Label` class for flexible label scaling.
- **Efficient Rendering**: Utilizes OpenGL shaders for optimized and smooth label rendering.

### Code Changes
1. **Feature Implementation**
   - Introduced the `Label` class to manage label rendering in 3D space.
   - Added the `Position` class to handle 3D coordinates.
   - Implemented billboard effect for label alignment with the camera.

2. **Shader Integration**
   - Added new GLSL vertex and fragment shaders for label rendering.

3. **Code Refactoring**
   - Reorganized OpenGL utilities into a dedicated `opengl` package.
   - Removed the deprecated `Label` data class and related tests.
   - Updated imports and references to reflect the new package structure.

4. **Testing Enhancements**
   - Updated and renamed tests from `LabelTest` to `LabelUtilsTest`.
   - Verified correct rendering and dynamic adjustment of labels.

## Still to implement
- [x] Label hooked to objects (e.g. Planet, Stars)
- [x] Little bit of code refactoring to avoid duplication of code etc.

### CODE REVIEW

**Comment by AdrienBousquieEPFL** [comment]
The code coverage reported in this PR pertains exclusively to OpenGL classes. As discussed with the team, testing OpenGL code—particularly in the domain of computer graphics—presents significant challenges. Given the complexity and the limited time available, we have determined that achieving comprehensive test coverage for this area is beyond our current scope.

As such, we acknowledge and accept the lower line coverage for this PR.

**Review by Ismaillat — APPROVED** [review]
The `Label` class implementation is a strong addition for rendering 3D text in an OpenGL environment. It effectively handles essential functionality such as creating, initializing, and rendering labels, while managing transformations like billboard rotation efficiently. The code is well-structured, leverages meaningful abstractions, and adheres to OpenGL standards.

There is, however, an opportunity for enhancement: making the label's size proportional to the zoom level. This adjustment would allow the label to scale dynamically as the user zooms in or out, improving usability.

Although the code coverage falls below the 80% threshold, this is understandable given the nature of OpenGL code, where certain elements are challenging to test comprehensively.

Overall, the implementation is solid and meets the requirements. The changes are well-done and approved for merge. Great work!

**Review by mehdi-hamirifou — DISMISSED** [review]
The label does not scale appropriately in relation to the zoom level which may disturb the UX.

**Comment by AdrienBousquieEPFL** [comment]
> The `Label` class implementation is a strong addition for rendering 3D text in an OpenGL environment. It effectively handles essential functionality such as creating, initializing, and rendering labels, while managing transformations like billboard rotation efficiently. The code is well-structured, leverages meaningful abstractions, and adheres to OpenGL standards.
> 
> There is, however, an opportunity for enhancement: making the label's size proportional to the zoom level. This adjustment would allow the label to scale dynamically as the user zooms in or out, improving usability.
> 
> Although the code coverage falls below the 80% threshold, this is understandable given the nature of OpenGL code, where certain elements are challenging to test comprehensively.
> 
> Overall, the implementation is solid and meets most of the requirements. However, it doesn't fully align with the scaling and visibility requirements. Apart from this, the changes are well-done and approved for merge. Great work!

Thank you @Ismaillat for the idea. I will try to implement this, I defined an issue for it:
- #304

**Pull request merged**
