### PR TITLE
feat: implement user registration functionality

### PR DESCRIPTION
**Pull request by othbcq**
This PR introduces the complete implementation of the registration functionality, including UI, ViewModel, repository, and tests. Below is a summary of the changes:

---

#### **Register Functionality**
- **RegisterScreen**:
  - Created a new composable with email/password input fields and a registration button.
  - Includes validation logic and integration with the ViewModel.

- **RegisterViewModel**:
  - Manages registration state and interacts with the repository.
  - Handles form validation and Firebase-based user creation.

- **RegisterRepositoryFirestore**:
  - Implements Firebase-based registration logic.
  - Abstracted via `RegisterRepository` interface for maintainability.

#### **UI Navigation Updates**
- Integrated `RegisterScreen` into `MainActivity` navigation flow.
- Added navigation from `SignIn` to `RegisterScreen`.

---

### Notes
This PR is part of a larger effort to split the previous login-related issue into three separate tasks. This specific PR focuses on the implementation of the user registration functionality.

### CODE REVIEW

**Review by mehdi-hamirifou — CHANGES_REQUESTED** [review]
The implementation provides a clean and modular registration feature. Nevertheless, requiring a minimal password length to enhance security would be great and a password confirmation field is a critical improvement to avoid user frustration caused by typos. Also, while error handling and validation are functional, there is room for improvement to make the code more robust and maintainable.

- In RegisterRepositoryFirestore : No error logging is done for auth.createUserWithEmailAndPassword. Exceptions should at least be logged for debugging. Example of refactoring: 
```ruby
override suspend fun registerUser(email: String, password: String) {
    try {
        auth.createUserWithEmailAndPassword(email, password).await()
    } catch (e: Exception) {
        Log.e("RegisterRepository", "Error creating user", e)
        throw e
    }
}
```
- In Register state: add confirm password field to the data class to support password confirmation. Example of data class:
```ruby
data class RegisterState(
    val email: String = "",
    val password: String = "",
    val confirmPassword: String = ""
)
```
- In RegisterScreen: A missing confirmation field can lead to user frustration due to registration errors caused by typos. Example of confirmation field: 
```ruby
OutlinedTextField(
    value = uiState.confirmPassword,
    onValueChange = { viewModel.onConfirmPasswordChanged(it) },
    label = { Text("Confirm Password", color = Color.White) },
    visualTransformation = PasswordVisualTransformation(),
    modifier = Modifier.fillMaxWidth().testTag("confirm_password_field"),
    textStyle = MaterialTheme.typography.bodyLarge.copy(color = Color.White),
    colors =
        TextFieldDefaults.outlinedTextFieldColors(
            focusedTextColor = Color.White,
            unfocusedTextColor = Color.White,
            focusedLabelColor = Color.White,
            unfocusedLabelColor = Color.Gray,
            focusedBorderColor = Color.White,
            unfocusedBorderColor = Color.Gray,
            cursorColor = Color.White)
)

```
- In RegisterViewModel: Need to  handle the update of confirm password and check  in registerUser function if the password's length is sufficient and if it matches the confirmation. Example of updates: 
```ruby
fun registerUser(confirmPassword: String, onSuccess: () -> Unit, onError: (String) -> Unit) {
    val email = _uiState.value.email
    val password = _uiState.value.password


    if (email.isBlank() || password.isBlank()) {
      onError("Email and password cannot be empty")
      return
    }

    if (password.length < 8) {
        onError("Password must be at least 8 characters")
        return
    }

    if (password != confirmPassword) {
        onError("Passwords do not match")
        return
    }

    viewModelScope.launch {
        try {
            repository.registerUser(email, password)
            onSuccess()
        } catch (e: Exception) {
            onError(e.localizedMessage ?: "Registration failed")
        }
    }
}

fun onConfirmPasswordChanged(confirmPassword: String) {
    _uiState.update { it.copy(confirmPassword = confirmPassword) }
}
```

**Review by mehdi-hamirifou — CHANGES_REQUESTED** [review]
Great job on implementing the fixes and improvements! The functionality and code structure look solid, and the changes significantly enhance the user experience and robustness.

That said, I noticed that the code could benefit from additional documentation or inline comments. Adding comments to explain key logic, especially in areas like registerUser in RegisterViewModel, would make it easier for others to understand and maintain the code in the future.

**Comment by othbcq** [comment]
> Great job on implementing the fixes and improvements! The functionality and code structure look solid, and the changes significantly enhance the user experience and robustness.
> 
> That said, I noticed that the code could benefit from additional documentation or inline comments. Adding comments to explain key logic, especially in areas like registerUser in RegisterViewModel, would make it easier for others to understand and maintain the code in the future.

Thank you for the feedback and for highlighting the importance of adding documentation to improve the code’s readability and maintainability.

I’ve gone ahead and added detailed documentation and inline comments throughout the code. The comments aim to clarify the logic and make the functionality easier to follow for future contributors.

Please let me know if there are any other areas where further improvements could be made.

Thanks again for your suggestions!

**Review by mehdi-hamirifou — APPROVED** [review]
Great work on adding the comments and documentation! The code is now clear and easy to follow, which will help the whole team. Everything looks good now. Approved for merge.

**Comment by othbcq** [comment]
@raniabbrk, Thank you for your earlier suggestion in the PR #197 regarding password validation in the login functionality. To enhance security and ensure stronger passwords, I’ve implemented your proposed changes directly in the registration code as part of this PR. This way, users will be guided to create secure passwords when registering their accounts.

Let me know if you have any further feedback or suggestions!

**Pull request merged**
