### PR TITLE
feat: implement quiz recap and score tracking

### PR DESCRIPTION
**Pull request by mehdi-hamirifou**
- Added QuizRepository to centralize quiz data handling, managing questions, score, and bestScore tracking
- Updated QuizViewModel to interact with QuizRepository, improving adherence to MVVM architecture
- Implemented score tracking to keep track of the best scores
- Added answer recap feature to allow users to review their responses at the end of the quiz
- Updated quiz selection screen to display best scores
- Updated quiz play screen end of quiz screen to display answers' results
- Refactored and updated test classes to validate new functionality and maintain test coverage

### CODE REVIEW

**Review by othbcq — CHANGES_REQUESTED** [review]
The code is well-structured and the quiz functionality works as expected. The composable setup is clear but there are some usability concerns with the answer button layout:

- The answer options display at the bottom of the screen.
- When a user selects an answer, the "Next Question" button appears at the bottom, causing the answer options to move up.
- On pressing "Next Question," the button disappears, and the answer options shift downward again.

This movement can feel disorienting for the users. 

Here's a possible version of the QuizPlayScreen composable with this problem fixed and with with some small changes for a better user experience.

```kotlin
@Composable
fun QuizPlayScreen(viewModel: QuizViewModel, navigationActions: NavigationActions) {
    val quizQuestions by viewModel.quizQuestions.observeAsState(emptyList())
    val currentQuestionIndex by viewModel.currentQuestionIndex.observeAsState(0)
    val selectedAnswer by viewModel.selectedAnswer.observeAsState(null)
    val score by viewModel.score.observeAsState(0)
    val showScore by viewModel.showScore.observeAsState(false)
    val quizTitle by viewModel.quizTitle.observeAsState("")

    BoxWithConstraints(modifier = Modifier.fillMaxSize()) {
        Image(
            painter = painterResource(id = R.drawable.landing_screen_bckgrnd),
            contentDescription = "Background",
            contentScale = ContentScale.Crop,
            modifier = Modifier.fillMaxSize().blur(8.dp).testTag("quiz_background")
        )

        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(horizontal = 24.dp, vertical = 16.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.SpaceBetween
        ) {
            Column(
                modifier = Modifier.fillMaxWidth(),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                if (!showScore) {
                    Button(
                        onClick = {
                            viewModel.resetQuiz()
                            navigationActions.navigateTo(Route.QUIZ)
                        },
                        modifier = Modifier.align(Alignment.Start),
                        colors = androidx.compose.material3.ButtonDefaults.buttonColors(
                            containerColor = Color.Red, contentColor = Color.White
                        ),
                        shape = RoundedCornerShape(8.dp)
                    ) {
                        Text(text = "Leave Quiz", textAlign = TextAlign.Center, fontSize = 16.sp)
                    }
                }

                Text(
                    text = "$quizTitle Quiz",
                    color = Color.White,
                    fontWeight = FontWeight.Bold,
                    fontSize = 28.sp,
                    modifier = Modifier.padding(vertical = 8.dp).testTag("quiz_title"),
                    textAlign = TextAlign.Center
                )
            }

            if (showScore) {
                Column(
                    horizontalAlignment = Alignment.CenterHorizontally,
                    verticalArrangement = Arrangement.spacedBy(16.dp),
                    modifier = Modifier.weight(1f) 
                ) {
                    Text(
                        text = "Your score: $score/${quizQuestions.size}",
                        color = Color.White,
                        fontSize = 28.sp,
                        fontWeight = FontWeight.Bold,
                        modifier = Modifier.testTag("score_text")
                    )

                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .weight(1f) 
                    ) {
                        QuizRecap(viewModel.getQuestions(), viewModel.getUserAnswers())
                    }
                }
            } else {
                quizQuestions.getOrNull(currentQuestionIndex)?.let { question ->
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(vertical = 16.dp),
                        horizontalAlignment = Alignment.CenterHorizontally,
                        verticalArrangement = Arrangement.spacedBy(16.dp)
                    ) {
                        Text(
                            text = question.question,
                            color = Color.White,
                            fontSize = 20.sp,
                            fontWeight = FontWeight.Bold,
                            modifier = Modifier.fillMaxWidth().testTag("quiz_question"),
                            textAlign = TextAlign.Center
                        )

                        Column(
                            modifier = Modifier.fillMaxWidth().padding(horizontal = 8.dp),
                            verticalArrangement = Arrangement.spacedBy(8.dp)
                        ) {
                            question.answers.forEachIndexed { index, answer ->
                                val backgroundColor = if (selectedAnswer == answer) Color(0xFFFF731F) else DarkPurple
                                Button(
                                    onClick = { viewModel.onAnswerSelected(answer) },
                                    colors = androidx.compose.material3.ButtonDefaults.buttonColors(
                                        containerColor = backgroundColor
                                    ),
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .height(40.dp)
                                        .testTag("answer_button_$index")
                                ) {
                                    Text(text = answer, fontSize = 16.sp, textAlign = TextAlign.Center)
                                }
                            }
                        }
                    }
                }
            }

            Button(
                onClick = {
                    if (showScore) {
                        viewModel.resetQuiz()
                        navigationActions.navigateTo(Route.QUIZ)
                    } else {
                        viewModel.goToNextQuestion()
                    }
                },
                enabled = selectedAnswer != null || showScore,
                colors = androidx.compose.material3.ButtonDefaults.buttonColors(
                    containerColor = if (selectedAnswer != null || showScore) Color(0xFF00C853) else Color.Gray,
                    contentColor = Color.White
                ),
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(vertical = 8.dp)
                    .height(56.dp)
                    .testTag(if (showScore) "return_to_quiz_selection_button" else "next_button")
            ) {
                Text(
                    text = if (showScore) "Return to Quiz Selection" else "Next Question",
                    fontSize = 18.sp,
                    textAlign = TextAlign.Center
                )
            }
        }
    }
}

**Review by Kenzoud — CHANGES_REQUESTED** [review]
Good job on your implementation! Your code has good structure. I just have a couple of comments.

UI : 

- It looks great overall. One suggestion I have is to increase the width of the buttons to ensure that the entire text is visible even for long answers (some answers are not entirely displayed in portrait mode). 

In the QuizViewModel:

- I believe that you should be using StateFlow instead of LiveData for the QuizViewModel. If you make this change, be sure to update QuizPlayScreen since it currently uses observeAsState(), which won't work with StateFlow. Instead, you'll need to use collectAsState().

- Also, since quizTitle only changes when a new quiz is loaded, it might be better to make it immutable. This would clarify its purpose, as it's not supposed to change during the quiz.

Ps: Since the setBestScore function is only used internally within QuizRepository, consider making it private.

**Review by Kenzoud — APPROVED** [review]
Good job on correctly integrating the requested changes. Now the code looks ready for merge.

**Review by othbcq — APPROVED** [review]
Everything looks good and works as expected. Approved for merge.

**Pull request merged**
