### PR TITLE
feat: implement edit image UI and delete image functionality

### PR DESCRIPTION
**Pull request by Ismaillat**
This pull request deals with issues #79 #163 #164.

### CODE REVIEW

**Review by mehdi-hamirifou — CHANGES_REQUESTED** [review]
Could you please add documentation and comments to your code to improve readability and make the review process easier?

**Comment by Ismaillat** [comment]
> Could you please add documentation and comments to your code to improve readability and make the review process easier?

I have added documentation and inline comments to all the modified files as requested. Thank you for your feedback. The code is now ready for your review. Please feel free to share any additional suggestions.

**Comment by Ismaillat** [comment]
> Great job! The implementation is solid, and the documentation is clear and comprehensive, making it easy to understand the different parts of the code. Here are a few suggestions to further enhance its robustness and maintainability:
> 
> ### 1. Improve `getPathFromUrl` Logic
> The `getPathFromUrl` function assumes a specific URL structure and lacks validation for null, empty, or malformed URLs. To address these issues:
> 
> Suggested Code:
> 
> ```kotlin
> private fun getPathFromUrl(url: String?): String {
>     require(!url.isNullOrBlank()) { "URL cannot be null or empty" }
>     val decodedUrl = URLDecoder.decode(url, StandardCharsets.UTF_8.toString())
>     return decodedUrl
>         .substringAfter("o/", "")
>         .substringBefore("?alt=media", "")
>         .ifEmpty { throw IllegalArgumentException("Invalid Firebase URL: $url") }
> }
> ```
> 
> ### 2. Add Edge-Case Tests for URL Validation
> Expand the test coverage for `getPathFromUrl` to handle edge cases like null, empty, and malformed URLs, as well as both encoded and decoded input formats.
> 
> Suggested Tests:
> 
> ```kotlin
> @Test(expected = IllegalArgumentException::class)
> fun `getPathFromUrl throws exception for null URL`() {
>     repository.getPathFromUrl(null)
> }
> 
> @Test(expected = IllegalArgumentException::class)
> fun `getPathFromUrl throws exception for empty URL`() {
>     repository.getPathFromUrl("")
> }
> 
> @Test
> fun `getPathFromUrl handles already-decoded URL`() {
>     val url = "https://firebase.storage/o/images/testImage.jpg?alt=media"
>     val result = repository.getPathFromUrl(url)
>     assertEquals("images/testImage.jpg", result)
> }
> 
> @Test
> fun `getPathFromUrl handles encoded URL`() {
>     val url = "https://firebase.storage/o/images%2FtestImage.jpg?alt=media"
>     val result = repository.getPathFromUrl(url)
>     assertEquals("images/testImage.jpg", result)
> }
> ```
> 
> These changes will improve error handling and ensure better test coverage. Good job overall!

Thank you for your detailed feedback and thoughtful suggestions. I have applied the requested changes, including improvements to the getPathFromUrl logic and additional test cases for edge scenarios.

I appreciate your insight, as it has helped enhance both the robustness and maintainability of the implementation. Please let me know if you have any additional suggestions or areas for improvement.

Looking forward to your review!

**Review by othbcq — APPROVED** [review]
Thank you for addressing the feedback and implementing the suggested changes. I reviewed the updates, and everything looks great! The additional test cases and improvements to the getPathFromUrl logic have enhanced the code's robustness and maintainability.

I don't have any further suggestions. Approving the PR for merge. Great job!

**Review by mehdi-hamirifou — APPROVED** [review]
Great job on implementing the Edit Image UI and Delete Image functionality ! I have nothing to add to Othmane's review. Approved for merge.

**Pull request merged**
